export type ContactMethod = { kind: "email" | "phone"; value: string; label?: string; is_primary: number };
export type Person = {
  id: string;
  name: string;
  preferred_name: string;
  first_name?: string;
  last_name?: string;
  nickname?: string;
  hometown?: string;
  location?: string;
  industry?: string;
  company?: string;
  headline?: string;
  job_title?: string;
  linkedin_url?: string;
  spike?: string;
  languages: string[];
  skills: string[];
  interests: string[];
  birthday?: string;
  relationship_strength: number;
  relationship?: string;
  when_met?: string;
  where_met?: string;
  how_met?: string;
  institutions: string[];
  mutuals: string[];
  last_contact?: string;
  tags: string[];
  notes?: string;
  quick_memories?: string;
  follow_up_date?: string;
  priority: number;
  warmth: number;
  intro_potential: number;
  source_confidence: number;
  sources: string[];
  methods: ContactMethod[];
  memory_count: number;
  interaction_count: number;
};

export type MemoryRecord = { id: string; raw_text: string; structured: Record<string, unknown>; source: string; occurred_at: string };
export type Interaction = { id: string; kind: string; occurred_at: string; summary?: string; source_connector: string; evidence: Record<string, unknown> };
export type Communication = {
  id: string;
  connector_id: string;
  external_id: string;
  guid?: string;
  source_rowid?: number;
  handle?: string;
  direction: "incoming" | "outgoing";
  kind: string;
  body?: string;
  occurred_at: string;
  role: "sender" | "participant";
  thread_external_id?: string;
  thread_title?: string;
  is_group: number;
  evidence: Record<string, unknown>;
};
export type CommunicationPage = { items: Communication[]; nextCursor: string | null };
export type Provenance = { id: string; field_name: string; field_value: string; connector_id: string; confidence: number; observed_at: string };
export type FullPerson = Person & { memories: MemoryRecord[]; interactions: Interaction[]; provenance: Provenance[]; identities: { id: string; connector_id: string; display_name: string; linked_by: string; confidence: number }[] };

export type ConnectorState = { connector_id: string; permission_state: string; status: string; last_sync_at?: string; last_error?: string; records_seen: number; records_linked: number };
export type SetupStatus = {
  phase: "welcome" | "contacts" | "messages" | "optional" | "complete";
  isFirstRun: boolean;
  isUsable: boolean;
  ownerDisplayName: string | null;
  completedAt: string | null;
  skippedSteps: string[];
  milestones: {
    hasPeople: boolean;
    peopleCount: number;
    contacts: { permission: string; status: string; synced: boolean; seen: number; error: string | null };
    messages: { readable: boolean; usingLocalCopy: boolean; messageCount: number | null; status: string; synced: boolean; seen: number; error: string | null };
  };
  nextAction: { step: string; label: string; route: string } | null;
};
export type Overview = { total: number; strongTies: number; cold: number; due: number; locations: [string, number][]; industries: [string, number][]; people: Person[]; coldPeople: Person[]; duePeople: Person[]; connectors: ConnectorState[]; setup: SetupStatus };
export type ParsedMemory = { candidates: { id: string; name: string; company?: string; score: number }[]; extracted: { memory: string; tags: string[]; followUpDate?: string; relationship?: string; interests?: string[] }; ambiguous: boolean };
export type Citation = { personId: string; label: string; field: string; value: string; source: string };
export type AgentAnswer = { answer: string; citations: Citation[]; provider: string };
